"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import ProtectedLayout from "../../protected-layout";
import { DataTable } from "../../components/ui/DataTable";

const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:4000";

type InvoiceStatus = "draft" | "sent" | "paid" | "overdue";

type Invoice = {
  id: string;
  periodStart: string;
  periodEnd: string;
  status: InvoiceStatus;
  totalAmount: number;
  currency: string;
  client: {
    id: string;
    firstName?: string | null;
    lastName?: string | null;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
};

function getClientName(client: Invoice["client"]) {
  if (client.name) return client.name;
  const parts = [client.firstName, client.lastName].filter(Boolean);
  return parts.length ? parts.join(" ") : "Unnamed client";
}

function StatusBadge({ status }: { status: InvoiceStatus }) {
  let colorClasses = "bg-gray-100 text-gray-700";

  if (status === "paid") {
    colorClasses = "bg-green-100 text-green-700";
  } else if (status === "sent") {
    colorClasses = "bg-blue-100 text-blue-700";
  } else if (status === "overdue") {
    colorClasses = "bg-red-100 text-red-700";
  } else if (status === "draft") {
    colorClasses = "bg-yellow-100 text-yellow-700";
  }

  return (
    <span
      className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${colorClasses}`}
    >
      {status.toUpperCase()}
    </span>
  );
}

export default function InvoicesPage() {
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState<string>("");
  const [clientNameFilter, setClientNameFilter] = useState<string>("");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchInvoices = async () => {
      const token = sessionStorage.getItem("token");

      if (!token) {
        setError("You are not logged in. Please log in again.");
        setLoading(false);
        return;
      }

      try {
        setLoading(true);
        setError(null);

        const params = new URLSearchParams();
        if (statusFilter) params.append("status", statusFilter);

        const url = `${API_BASE_URL}/api/invoices?${params.toString()}`;
        console.log("🔍 Fetching invoices from:", url);

        const res = await fetch(url, {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });

        const data = await res.json();

        if (!res.ok) {
          console.error("❌ Invoices API error:", res.status, data);
          setError(data.error || "Failed to load invoices.");
          setInvoices([]);
          setLoading(false);
          return;
        }

        setInvoices(data ?? []);
        setLoading(false);
      } catch (err: any) {
        console.error("❌ Network or code error:", err);
        setError(err.message ?? "Something went wrong loading invoices.");
        setLoading(false);
      }
    };

    fetchInvoices();
  }, [statusFilter]);

  const visibleInvoices =
    clientNameFilter.trim().length === 0
      ? invoices
      : invoices.filter((inv) =>
          getClientName(inv.client)
            .toLowerCase()
            .includes(clientNameFilter.toLowerCase())
        );

  const columns = [
    {
      key: "client",
      header: "Client",
      render: (inv: Invoice) => getClientName(inv.client),
    },
    {
      key: "period",
      header: "Period",
      render: (inv: Invoice) =>
        `${new Date(inv.periodStart).toLocaleDateString()} – ${new Date(
          inv.periodEnd
        ).toLocaleDateString()}`,
    },
    {
      key: "status",
      header: "Status",
      render: (inv: Invoice) => <StatusBadge status={inv.status} />,
    },
    {
      key: "totalAmount",
      header: "Total",
      render: (inv: Invoice) =>
        `${inv.currency} ${inv.totalAmount.toFixed(2)}`,
      className: "text-right",
    },
    {
      key: "actions",
      header: "",
      render: (inv: Invoice) => (
        <Link
          href={`/billing/${inv.id}`}
          className="rounded-md border border-gray-200 px-3 py-1 text-xs font-medium text-gray-700 hover:bg-gray-50"
        >
          View
        </Link>
      ),
      className: "text-right",
    },
  ];

  return (
    <ProtectedLayout>
      <div className="mx-auto flex max-w-5xl flex-col gap-6 px-4 py-6 lg:px-6">
        <header className="flex flex-col gap-1">
          <h1 className="text-2xl font-semibold tracking-tight text-gray-900">
            Invoices
          </h1>
          <p className="text-sm text-gray-500">
            All invoices generated by ElderFlow for this organization.
          </p>
        </header>

        <section className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
          <div className="flex flex-wrap items-center gap-4">
            <div className="flex items-center gap-2">
              <label className="text-sm font-medium text-gray-700">
                Status
              </label>
              <select
                className="rounded-md border border-gray-200 bg-white px-3 py-1.5 text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
              >
                <option value="">All</option>
                <option value="draft">Draft</option>
                <option value="sent">Sent</option>
                <option value="paid">Paid</option>
                <option value="overdue">Overdue</option>
              </select>
            </div>

            <div className="flex items-center gap-2">
              <label className="text-sm font-medium text-gray-700">
                Client name
              </label>
              <input
                type="text"
                className="w-56 rounded-md border border-gray-200 bg-white px-3 py-1.5 text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Filter by client name"
                value={clientNameFilter}
                onChange={(e) => setClientNameFilter(e.target.value)}
              />
            </div>
          </div>
        </section>

        <section>
          {error ? (
            <div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
              {error}
            </div>
          ) : (
            <DataTable
              columns={columns}
              data={visibleInvoices}
              loading={loading}
              emptyMessage="No invoices match this filter. Try changing the status or client name."
            />
          )}
        </section>
      </div>
    </ProtectedLayout>
  );
}
